=== Alphapuppy/gcam-core/CIAM/Ciam.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Son H. Kim (JGCRI) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="scenario">
		<xs:annotation>
			<xs:documentation>This is the scenario class</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="summary" type="xs:string"/>
				<xs:element name="modeltime">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="startyear" type="xs:integer"/>
							<xs:element name="interyear1" type="xs:integer"/>
							<xs:element name="interyear2" type="xs:integer"/>
							<xs:element name="endyear" type="xs:integer"/>
							<xs:element name="timestep1" type="xs:integer"/>
							<xs:element name="timestep2" type="xs:integer"/>
							<xs:element name="timestep3" type="xs:integer"/>
							<xs:element name="popbegin" type="xs:integer"/>
							<xs:element name="dataend" type="xs:integer"/>
							<xs:element name="datatimestep" type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="world">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="region" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="demographics">
											<xs:annotation>
												<xs:documentation/>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="population" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="year" type="xs:integer"/>
																<xs:element name="total" type="xs:integer"/>
																<xs:element ref="datainfo"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="laborproductivity" maxOccurs="unbounded">
														<xs:annotation>
															<xs:documentation>Growth rate</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element name="year" type="xs:integer"/>
																<xs:element name="growthrate" type="xs:float"/>
																<xs:element ref="datainfo"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="laborforce" maxOccurs="unbounded">
														<xs:annotation>
															<xs:documentation>Participation rate</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element name="year" type="xs:integer"/>
																<xs:element name="part_rate" type="xs:float"/>
																<xs:element ref="datainfo"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="resource" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="market" type="xs:string"/>
													<xs:element name="price" type="xs:double"/>
													<xs:element name="subresource" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="name" type="xs:Name"/>
																<xs:element name="period" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="grade" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="name" type="xs:Name"/>
																						<xs:element name="year" type="xs:integer"/>
																						<xs:element name="available" type="xs:double"/>
																						<xs:element name="extractioncost" type="xs:double"/>
																						<xs:element name="environmentalcost" type="xs:double"/>
																						<xs:element name="severencetax" type="xs:double"/>
																						<xs:element name="techchange" type="xs:double"/>
																						<xs:element name="datainfo">
																							<xs:complexType>
																								<xs:sequence>
																									<xs:element name="unit" type="xs:string"/>
																									<xs:element name="source" type="xs:string"/>
																									<xs:element name="note" type="xs:string"/>
																								</xs:sequence>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="supplysector" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:Name"/>
													<xs:element name="market" type="xs:string"/>
													<xs:element name="price" type="xs:double"/>
													<xs:element ref="subsector" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="demandsector" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:Name"/>
													<xs:element name="market" type="xs:string"/>
													<xs:element name="price" type="xs:double"/>
													<xs:element name="serviceoutput" type="xs:double"/>
													<xs:element name="energyconsumption" type="xs:double"/>
													<xs:element name="priceelasticity" type="xs:double"/>
													<xs:element name="incomeelasticity" type="xs:double"/>
													<xs:element ref="subsector" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="ghgmarket" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="ghgname" type="xs:Name"/>
													<xs:element name="year" type="xs:integer"/>
													<xs:element name="market" type="xs:string"/>
													<xs:element name="constraint" type="xs:double"/>
													<xs:element name="note" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="date" type="xs:dateTime" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="datainfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="unit" type="xs:string"/>
				<xs:element name="source" type="xs:string"/>
				<xs:element name="note" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="period">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="grade" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:Name"/>
							<xs:element name="year" type="xs:integer"/>
							<xs:element name="available" type="xs:double"/>
							<xs:element name="extractioncost" type="xs:double"/>
							<xs:element name="environmentalcost" type="xs:double"/>
							<xs:element name="severencetax" type="xs:double"/>
							<xs:element name="techchange" type="xs:double"/>
							<xs:element name="datainfo">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="unit" type="xs:string"/>
										<xs:element name="source" type="xs:string"/>
										<xs:element name="note" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="technology">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="period" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:Name"/>
							<xs:element name="year" type="xs:integer"/>
							<xs:element name="fuelname" type="xs:Name"/>
							<xs:element name="sharewt" type="xs:double"/>
							<xs:element name="efficiency" type="xs:double"/>
							<xs:element name="nonenergycost" type="xs:double"/>
							<xs:element name="tax" type="xs:double"/>
							<xs:element name="logitexp" type="xs:double"/>
							<xs:element name="techchange" type="xs:double"/>
							<xs:element name="datainfo">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="unit" type="xs:string"/>
										<xs:element name="source" type="xs:string"/>
										<xs:element name="note" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="GHG" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:Name"/>
										<xs:element name="unit" type="xs:Name"/>
										<xs:element name="emisscoef" type="xs:double"/>
										<xs:element name="removefrac" type="xs:double"/>
										<xs:element name="GWP" type="xs:double"/>
										<xs:element name="datainfo">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="unit" type="xs:string"/>
													<xs:element name="source" type="xs:string"/>
													<xs:element name="note" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="subsector">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:Name"/>
				<xs:element name="capacitylimit" type="xs:double"/>
				<xs:element name="sharewt" type="xs:double"/>
				<xs:element name="logitexp" type="xs:double"/>
				<xs:element ref="technology" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Alphapuppy/gcam-core/CIAM/reference.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Son H. Kim (JGCRI) -->
<!--Sample XML file generated by XMLSPY v5 rel. 2 U (http://www.xmlspy.com)-->
<scenario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\PNNL\CIAM\INPUT\myxml\Ciam.xsd" name="ReferenceScenario" date="2003-01-03T13:40:47-05:00">
	<summary>Reference Scenario based on SRES B2 Scenario</summary>
	<modeltime>
		<startyear>1975</startyear>
		<interyear1>2005</interyear1>
		<interyear2>2050</interyear2>
		<endyear>2095</endyear>
		<timestep1>15</timestep1>
		<timestep2>15</timestep2>
		<timestep3>15</timestep3>
		<popbegin>1960</popbegin>
		<dataend>2095</dataend>
		<datatimestep>15</datatimestep>
	</modeltime>
	<world>
		<region name="USA">
			<demographics>
				<population>
					<year>1960</year>
					<total>180738</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>1975</year>
					<total>216067</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>1990</year>
					<total>249012</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>2005</year>
					<total>291604</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>2020</year>
					<total>327682</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>2035</year>
					<total>361786</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>2050</year>
					<total>384810</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>2065</year>
					<total>406002</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>2080</year>
					<total>432120</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>2095</year>
					<total>457962</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<laborproductivity>
					<year>1975</year>
					<growthrate>0.017</growthrate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborproductivity>
				<laborproductivity>
					<year>1990</year>
					<growthrate>0.0118239</growthrate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborproductivity>
				<laborproductivity>
					<year>2005</year>
					<growthrate>0.01622415</growthrate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborproductivity>
				<laborproductivity>
					<year>2020</year>
					<growthrate>0.01321581</growthrate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborproductivity>
				<laborproductivity>
					<year>2035</year>
					<growthrate>0.01150848</growthrate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborproductivity>
				<laborproductivity>
					<year>2050</year>
					<growthrate>0.00763224</growthrate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborproductivity>
				<laborproductivity>
					<year>2065</year>
					<growthrate>0.00896513</growthrate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborproductivity>
				<laborproductivity>
					<year>2080</year>
					<growthrate>0.00937597</growthrate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborproductivity>
				<laborproductivity>
					<year>2095</year>
					<growthrate>0.01166821</growthrate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborproductivity>
				<laborforce>
					<year>1975</year>
					<part_rate>0.45</part_rate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborforce>
				<laborforce>
					<year>1990</year>
					<part_rate>0.5</part_rate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborforce>
				<laborforce>
					<year>2005</year>
					<part_rate>0.52</part_rate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborforce>
				<laborforce>
					<year>2020</year>
					<part_rate>0.52</part_rate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborforce>
				<laborforce>
					<year>2035</year>
					<part_rate>0.49</part_rate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborforce>
				<laborforce>
					<year>2050</year>
					<part_rate>0.49</part_rate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborforce>
				<laborforce>
					<year>2065</year>
					<part_rate>0.48</part_rate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborforce>
				<laborforce>
					<year>2080</year>
					<part_rate>0.47</part_rate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborforce>
				<laborforce>
					<year>2095</year>
					<part_rate>0.45</part_rate>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</laborforce>
			</demographics>
			<resource name="crude oil">
				<market>String</market>
				<price>3.14159265358979</price>
				<subresource>
					<name>Name</name>
					<period>
						<grade>
							<name>grade1</name>
							<year>1975</year>
							<available/>
							<extractioncost/>
							<environmentalcost/>
							<severencetax/>
							<techchange/>
							<datainfo>
								<unit/>
								<source/>
								<note/>
							</datainfo>
						</grade>
					</period>
				</subresource>
			</resource>
			<supplysector>
				<name>electricity</name>
				<market>String</market>
				<price>3.14159265358979</price>
				<subsector>
					<name>coal</name>
					<capacitylimit>3.14159265358979</capacitylimit>
					<sharewt>3.14159265358979</sharewt>
					<logitexp>3.14159265358979</logitexp>
					<technology>
						<period>
							<name>pulverized_coal</name>
							<year>1975</year>
							<fuelname>coal</fuelname>
							<sharewt/>
							<efficiency/>
							<nonenergycost/>
							<tax/>
							<logitexp/>
							<techchange/>
							<datainfo>
								<unit/>
								<source/>
								<note/>
							</datainfo>
							<GHG>
								<name>CO2</name>
								<unit>MTC</unit>
								<emisscoef/>
								<removefrac/>
								<GWP/>
								<datainfo>
									<unit/>
									<source/>
									<note/>
								</datainfo>
							</GHG>
						</period>
					</technology>
				</subsector>
			</supplysector>
			<demandsector>
				<name>transportation</name>
				<market>String</market>
				<price>3.14159265358979</price>
				<serviceoutput>3.14159265358979</serviceoutput>
				<energyconsumption>3.14159265358979</energyconsumption>
				<priceelasticity>3.14159265358979</priceelasticity>
				<incomeelasticity>3.14159265358979</incomeelasticity>
				<subsector>
					<name>passenger</name>
					<capacitylimit>3.14159265358979</capacitylimit>
					<sharewt>3.14159265358979</sharewt>
					<logitexp>3.14159265358979</logitexp>
					<technology>
						<period>
							<name>automobile</name>
							<year>1975</year>
							<fuelname>gasoline</fuelname>
							<sharewt/>
							<efficiency/>
							<nonenergycost/>
							<tax/>
							<logitexp/>
							<techchange/>
							<datainfo>
								<unit/>
								<source/>
								<note/>
							</datainfo>
							<GHG>
								<name>CO2</name>
								<unit>MTC</unit>
								<emisscoef/>
								<removefrac/>
								<GWP/>
								<datainfo>
									<unit/>
									<source/>
									<note/>
								</datainfo>
							</GHG>
						</period>
					</technology>
				</subsector>
			</demandsector>
			<ghgmarket>
				<ghgname>Name</ghgname>
				<year>0</year>
				<market>String</market>
				<constraint>3.14159265358979</constraint>
				<note>String</note>
			</ghgmarket>
		</region>
		<region name="Canada">
			<demographics>
				<population>
					<year>1960</year>
					<total>17909</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>1975</year>
					<total>23209</total>
					<datainfo>
						<unit>String</unit>
						<source>String</source>
						<note>String</note>
					</datainfo>
				</population>
				<population>
					<year>1990</year>
					<total>29003</total>
